# This file was generated by GoReleaser. DO NOT EDIT.
class Cw < Formula
  desc "The best way to tail AWS Cloudwatch Logs from your terminal"
  homepage "https://www.lucagrulla.com/cw"
  version "3.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lucagrulla/cw/releases/download/v3.2.1/cw_3.2.1_Darwin_x86_64.tar.gz"
    sha256 "ef0ce7be02cdb37952864791bd9fd44d64750cf7f9a85b568aae6aa4d9488487"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lucagrulla/cw/releases/download/v3.2.1/cw_3.2.1_Linux_x86_64.tar.gz"
      sha256 "c7e0192bc872f73a61fa70c258996c969be86bf85b2e192a5ac0e710f4ee8f8a"
    end
  end

  def install
    bin.install "cw"
    
    system bin/"cw --completion-script-bash > cw.bash"
    bash_completion.install "cw.bash"
    
    system bin/"cw --help-man > cw.1"
    man1.install "cw.1"
    
    # system bin/"cw completion zsh > cw.zsh"
    # zsh_completion.install "cw.zsh"
  end

  def caveats; <<~EOS
    In order to get cw completion, [bash] you need to install `bash-completion` with brew. OR [zsh], add the following line to your ~/.zshrc: source #{HOMEBREW_PREFIX}/share/zsh/site-functions/cw
  EOS
  end
end
