# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cw < Formula
  desc "The best way to tail AWS Cloudwatch Logs from your terminal"
  homepage "https://www.lucagrulla.com/cw"
  version "4.0.5"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lucagrulla/cw/releases/download/v4.0.5/cw_4.0.5_Darwin_x86_64.tar.gz"
    sha256 "89c432cc2319cc919a2124d6ed676c6611d5de5d39ab33d2ec3196005b30c433"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lucagrulla/cw/releases/download/v4.0.5/cw_4.0.5_Darwin_arm64.tar.gz"
    sha256 "29452349ea9075460c0dab5568bae0c8b45299279dd65d9c420f6076d995fd54"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lucagrulla/cw/releases/download/v4.0.5/cw_4.0.5_Linux_x86_64.tar.gz"
    sha256 "fd8c2775e7fc113141010d655a5db85aa3aec01d3494ace66c5dcc2baa6480ce"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/lucagrulla/cw/releases/download/v4.0.5/cw_4.0.5_Linux_armv6.tar.gz"
    sha256 "b4450a68f908e874153ad5853e53bfb81a5a53e0a62a8eba8fa38d9eb6823385"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lucagrulla/cw/releases/download/v4.0.5/cw_4.0.5_Linux_arm64.tar.gz"
    sha256 "6743606f25b2da51eeb61342f2f163ec896f3a69062c3ec56862252f15974db2"
  end

  def install
    bin.install "cw"

    bash_completion.install "cw.bash"
    zsh_completion.install "cw.zsh"
  end

  def caveats; <<~EOS
    In order to get cw completion, [bash] you need to install `bash-completion` with brew. OR [zsh], add the following line to your ~/.zshrc: source #{HOMEBREW_PREFIX}/share/zsh/site-functions/cw
  EOS
  end
end
