# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heracles < Formula
  desc "Your favourite Fitbit-> Withings scale data importer"
  homepage "https://github.com/lucagrulla/heracles"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lucagrulla/heracles/releases/download/v0.1.1/heracles_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "21f30dfb7d4cd7973ad7e8352075362286506e3f60eb25a90bea643018124c90"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lucagrulla/heracles/releases/download/v0.1.1/heracles_0.1.1_Linux_x86_64.tar.gz"
    sha256 "0898c6062023d461990eff27a72a83ff376c48bff9f1a0286c0532661ba9baeb"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/lucagrulla/heracles/releases/download/v0.1.1/heracles_0.1.1_Linux_armv6.tar.gz"
    sha256 "5afe10644fe5da877679e115ab67f5248acb62244b3d94d401989e4f88a38cc5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lucagrulla/heracles/releases/download/v0.1.1/heracles_0.1.1_Linux_arm64.tar.gz"
    sha256 "4191a7ba8230adf9474933f4a76e74dbfb0da6bf05a88aeb1ecf4a2889089fae"
  end

  def install
    bin.install "heracles"
  end
end
