# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heracles < Formula
  desc "Your favourite Fitbit-> Withings scale data importer"
  homepage "https://github.com/lucagrulla/heracles"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucagrulla/heracles/releases/download/v0.1.4/heracles_0.1.4_Darwin_arm64.tar.gz"
      sha256 "b87fb9cba88c188e4febde983374e94e6eb8426583d8df2fea00425915d02067"

      def install
        bin.install "heracles"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucagrulla/heracles/releases/download/v0.1.4/heracles_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "376a472fcb47accfdb25bf445c186a641fabe742dae87bccdfebda8fa928be01"

      def install
        bin.install "heracles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucagrulla/heracles/releases/download/v0.1.4/heracles_0.1.4_Linux_arm64.tar.gz"
      sha256 "0ee1fbfe04514526394440015efa8ccbe6106c66c918ca616dccfaa20bb3ebdc"

      def install
        bin.install "heracles"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucagrulla/heracles/releases/download/v0.1.4/heracles_0.1.4_Linux_x86_64.tar.gz"
      sha256 "46cc17d1062abc96e75be74fb695100de11ed4db61e32fbd3249209f740b17c9"

      def install
        bin.install "heracles"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lucagrulla/heracles/releases/download/v0.1.4/heracles_0.1.4_Linux_armv6.tar.gz"
      sha256 "9e55e738f92fc2e46823d780f26e3847420cc055f9c4ac7035157bdb9900523f"

      def install
        bin.install "heracles"
      end
    end
  end
end
